# NUMPY:

* Numerical Python
* Python library used for working with Arrays
* Created in 2005 by Travis Oliphant
* Lists that serve the purpose of arrays but slow to process
* Numpy aims to provide an array object that is upto 50x faster than traditional python lists

In [1]:
import numpy as np
import sys
s=range(1000)
print("size of each element of lists in bytes:", sys.getsizeof(s))
print("print size of whole list in bytes:", sys.getsizeof(s)*len(s))

size of each element of lists in bytes: 48
print size of whole list in bytes: 48000


In [2]:
D=np.arange(1000)
print("size of each element of numpy array in bytes:", D.itemsize)
print("print size of whole numpy array in bytes:", D.itemsize*D.size)

size of each element of numpy array in bytes: 4
print size of whole numpy array in bytes: 4000


In [3]:
import numpy as np
arr=np.array(42)
print(arr)
print(arr.ndim)
print(type(arr))

42
0
<class 'numpy.ndarray'>


In [4]:
import numpy as np
arr=np.array([42])
print(arr)
print(arr.ndim)
print(type(arr))

[42]
1
<class 'numpy.ndarray'>


In [5]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.ndim)
print(type(arr))

[1 2 3 4 5]
1
<class 'numpy.ndarray'>


In [12]:
import numpy as np
arr=np.array([[1,2,3],[6,7,8]])
print(arr)
print("dimensions=",arr.ndim)
print(type(arr))

[[1 2 3]
 [6 7 8]]
dimensions= 2
<class 'numpy.ndarray'>


In [11]:
import numpy as np
arr=np.array([[1,2,3],[6,7]])
print(arr)
print("dimensions=",arr.ndim)
print(type(arr))
# the size of the elements must be same or else it gives error

[list([1, 2, 3]) list([6, 7])]
dimensions= 1
<class 'numpy.ndarray'>


<ipython-input-11-e1945c583a7d>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr=np.array([[1,2,3],[6,7]])


no of dimension equals number of brackets at the start of the list definition

In [14]:
import numpy as np
arr=np.array([[[1,2,3],[6,7,3]],[[1,7,4],[6,9,1]]])
print(arr)
print("dimensions=",arr.ndim)
print(type(arr))

[[[1 2 3]
  [6 7 3]]

 [[1 7 4]
  [6 9 1]]]
dimensions= 3
<class 'numpy.ndarray'>


In [15]:
import numpy as np
arr=np.array([[[1,2,3,4,5]]])
print(arr)
print("dimensions=",arr.ndim)
print(type(arr))

[[[1 2 3 4 5]]]
dimensions= 3
<class 'numpy.ndarray'>


In [16]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[3])
print(arr[2]+arr[4])

4
8


In [18]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[0,1])
print(arr[1,1])
print(arr[0,3])
print(arr[1,2])

2
6
4
7


In [21]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])
print(arr[1,1,1])
print(arr[0,0,1])
print(arr[1,0,2])
print(arr[2,2,0])   # this gives error as it does not exist

6
11
2
9


IndexError: index 2 is out of bounds for axis 0 with size 2

In [23]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[1,-1])  #gives 0 dimension
print(arr[0,-3])  #gives 0 dimension
print(arr[1,0:3])  #gives 1 dimension
print(arr[1:2,0:3])  # gives 2 dimension
print(arr[0:2,2])   #gives 2 dimension

8
2
[5 6 7]
[[5 6 7]]
[3 7]


In [24]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0:2,0:2,0:2])

[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]


In [27]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0:2,1,0:2]) #2D
print(arr[0:2,1,2]) #1D

[[ 4  5]
 [10 11]]
[ 6 12]


### Shape:

In [30]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([[1,2,3,4],[5,6,7,8]])
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr1.ndim)
print(arr1.shape)

print(arr2.ndim)
print(arr2.shape)

print(arr3.ndim)
print(arr3.shape)


1
(5,)
2
(2, 4)
3
(2, 2, 3)


In [31]:
import numpy as np
arr=np.array([1,2,3,4,5],ndmin=5)
print(arr)

[[[[[1 2 3 4 5]]]]]


### Reshape:

In [35]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
newarr=arr1.reshape(2,3)
print(newarr)
newarr1=arr1.reshape(3,2)
print(newarr1)
newarr2=arr1.reshape(1,6)
print(newarr2)
newarr3=arr1.reshape(6,1)
print(newarr3)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [36]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
newarr=arr1.reshape(2,-1)
print(newarr)
newarr1=arr1.reshape(3,-1)
print(newarr1)


[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [38]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
newarr=arr1.reshape(2,-1).base  #.base gives original shape
print(newarr)

[1 2 3 4 5 6]


## Iteration:

In [41]:
import numpy as np
arr=np.array([[1,2,3,4,5]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5


In [42]:
import numpy as np
arr=np.array([[[1,2,3,4,5]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5


##### nditer

In [44]:
import numpy as np
arr=np.array([[[1,2,3,4,5]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5


In [48]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr[0:1,::2]):
    print(x)

1
3


In [50]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr[:,::2]):
    print(x)

1
3
5
7


## Built in Functions:


###### 1.concatenate()

In [53]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.array([7,8,9])
arr=np.concatenate((arr1,arr2,arr3))
print(arr)

[1 2 3 4 5 6 7 8 9]


In [54]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6,11])
arr3=np.array([7,8])
arr=np.concatenate((arr1,arr2,arr3))
print(arr)

[ 1  2  3  4  5  6 11  7  8]


In [57]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6,11])
arr3=np.array([7,8])
arr=np.concatenate((arr1,arr2,arr3),axis=0)
print(arr)

[ 1  2  3  4  5  6 11  7  8]


In [58]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6,11])
arr3=np.array([7,8])
arr=np.concatenate((arr1,arr2,arr3),axis=1)
print(arr)

AxisError: axis 1 is out of bounds for array of dimension 1

In [61]:
import numpy as num
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=0)
print(arr)
print("shape=",arr.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
shape= (4, 2)


In [62]:
import numpy as num
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)
print("shape=",arr.shape)

[[1 2 5 6]
 [3 4 7 8]]
shape= (2, 4)


* axis=0 =>combines elements horizontally
* axis=1 =>combines elements vertically in the same index

#### 2. split

In [65]:
import numpy as np
arr=np.array([1,2,3,4])
newarr=np.array_split(arr,4)
print(newarr)

[array([1]), array([2]), array([3]), array([4])]


In [66]:
import numpy as np
arr=np.array([1,2,3,4])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3]), array([4])]


In [67]:
import numpy as np
arr=np.array([1,2,3,4])
newarr=np.array_split(arr,2)
print(newarr)

[array([1, 2]), array([3, 4])]


In [68]:
import numpy as np
arr=np.array([1,2,3,4])
newarr=np.array_split(arr,1)
print(newarr)

[array([1, 2, 3, 4])]


In [69]:
import numpy as np
arr=np.array([1,2,3,4])
newarr=np.array_split(arr,5)
print(newarr)

[array([1]), array([2]), array([3]), array([4]), array([], dtype=int32)]


In [72]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
newarr=np.array_split(arr,4)
print(newarr)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]]), array([[10, 11, 12]])]


In [74]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
newarr=np.array_split(arr,3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9]]), array([[10, 11, 12]])]


In [73]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
newarr=np.array_split(arr,4,axis=1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10]]), array([[ 2],
       [ 5],
       [ 8],
       [11]]), array([[ 3],
       [ 6],
       [ 9],
       [12]]), array([], shape=(4, 0), dtype=int32)]


##### 3. where()

In [75]:
import numpy as np
arr=np.array([1,2,3,4,5,6,4])
x=np.where(arr==4)
print(x)

(array([3, 6], dtype=int64),)


In [77]:
import numpy as np
arr=np.array([1,2,3,4,5,6,4])
x=np.where(arr%2==0)
print(x)  # answer is givne in form of indices

(array([1, 3, 5, 6], dtype=int64),)


In [79]:
import numpy as np
arr=np.array([[1,2],[3,4],[4,5],[7,8]])
x=np.where(arr==4)
print(x)

(array([1, 2], dtype=int64), array([1, 0], dtype=int64))


In [80]:
import numpy as np
arr=np.array([[1,2],[3,4],[4,5],[7,8]])
x=np.where(arr==3)
print(x)

(array([1], dtype=int64), array([0], dtype=int64))
