In [1]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,3]],[[3,4,6],[7,3,2]]])
x=np.where(arr==3)
print(x)

(array([0, 0, 1, 1], dtype=int64), array([0, 1, 0, 1], dtype=int64), array([2, 2, 0, 1], dtype=int64))


* 0 0 1 1
* 0 1 0 1
* 2 2 0 1


* read this vertically as 0 0 2 , 0 1 2 , 1 0 0 , 1 1 1  these are the positions of "3 "

#### 4.sort()

In [3]:
import numpy as np 
arr1 = np.array([1,2,3,4,5,4,6,7])
print(np.sort(arr1))

[1 2 3 4 4 5 6 7]


In [5]:
import numpy as np 
arr2=np.array(["banana","apple","cherry"])
print(np.sort(arr2))

['apple' 'banana' 'cherry']


In [6]:
import numpy as np 
arr3=np.array([True,False,True])
print(np.sort(arr3))

[False  True  True]


In [10]:
import numpy as np 
arr4=np.array([[3,4,2],[1,7,3],[4,2,5]])
print(np.sort(arr4))
#sorts each bracket individually

[[2 3 4]
 [1 3 7]
 [2 4 5]]


here axis is given inside sort function so this is different than the axis use previously

In [11]:
import numpy as np 
arr4=np.array([[3,4,2],[1,7,3],[4,2,5]])
print(np.sort(arr4,axis=0))  # by default value of axis = -1
#does column wise sorting.....while checking each bracket...

[[1 2 2]
 [3 4 3]
 [4 7 5]]


In [12]:
import numpy as np 
arr4=np.array([[3,4,2],[1,7,3],[4,2,5]])
print(np.sort(arr4,axis=1))  # by default value of axis = -1
# same as axis=1

[[2 3 4]
 [1 3 7]
 [2 4 5]]


In [13]:
import numpy as np 
arr4=np.array([[3,4,2],[1,7,3],[4,2,5]])
print(np.sort(arr4,axis=None))

[1 2 2 3 3 4 4 5 7]


In [15]:
import numpy as np 
arr=np.array([[[3,2,8],[7,9,3]],[[6,7,2],[9,6,4]]])
np.sort(arr,axis=-1)  
#sorts bracket-wise

array([[[2, 3, 8],
        [3, 7, 9]],

       [[2, 6, 7],
        [4, 6, 9]]])

In [16]:
import numpy as np 
arr=np.array([[[3,2,8],[7,9,3]],[[6,7,2],[9,6,4]]])
np.sort(arr,axis=0) 
#doubtful...

array([[[3, 2, 2],
        [7, 6, 3]],

       [[6, 7, 8],
        [9, 9, 4]]])

compares [3,2,8] with [6,7,2] and [7,9,3] with [9,6,4]

In [17]:
import numpy as np 
arr=np.array([[[3,2,8],[7,9,3]],[[6,7,2],[9,6,4]]])
np.sort(arr,axis=1) 
#doubtful...

array([[[3, 2, 3],
        [7, 9, 8]],

       [[6, 6, 2],
        [9, 7, 4]]])